# Generated by Django 3.1.4 on 2021-01-11 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(db_index=True, max_length=20, verbose_name='Марка')),
                ('model', models.CharField(db_index=True, max_length=20, verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Марка и модель',
                'verbose_name_plural': 'Марки и модели',
                'ordering': ['mark'],
            },
        ),
        migrations.CreateModel(
            name='Transmissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='Коробки передач')),
            ],
            options={
                'verbose_name': 'Коробка передач',
                'verbose_name_plural': 'Коробки передач',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Цена')),
                ('mileage', models.IntegerField(blank=True, null=True, verbose_name='Пробег')),
                ('litre', models.SmallIntegerField(blank=True, null=True, verbose_name='Литраж')),
                ('speed', models.SmallIntegerField(blank=True, null=True, verbose_name='Максимальная скорость')),
                ('release', models.DateField(blank=True, null=True, verbose_name='Дата выпуска')),
                ('reservation', models.BooleanField(blank=True, verbose_name='Резерв')),
                ('stamp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Cars.marks', verbose_name='Марка - Модель')),
                ('transmission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Cars.transmissions', verbose_name='КПП')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'ordering': ['stamp'],
            },
        ),
    ]
