# Generated by Django 3.1.4 on 2021-01-12 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0002_auto_20210111_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='mileage',
        ),
        migrations.AlterField(
            model_name='cars',
            name='litre',
            field=models.FloatField(blank=True, null=True, verbose_name='Литраж'),
        ),
    ]
