# Generated by Django 3.1.4 on 2021-01-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bsles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stamp', models.CharField(max_length=50, verbose_name='Марка')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Цена')),
                ('release', models.DateField(blank=True, null=True, verbose_name='Дата выпуска')),
                ('reservation', models.BooleanField(blank=True, verbose_name='Резерв')),
            ],
            options={
                'verbose_name': 'Велосипед',
                'verbose_name_plural': 'Велосипеды',
                'ordering': ['stamp'],
            },
        ),
    ]
