# Generated by Django 3.1.4 on 2021-01-14 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bicycles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='Рамы')),
                ('abb', models.CharField(db_index=True, max_length=20, verbose_name='Аббривиатура')),
            ],
            options={
                'verbose_name': 'Рама',
                'verbose_name_plural': 'Рамы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(db_index=True, max_length=20, verbose_name='Марка')),
                ('model', models.CharField(db_index=True, max_length=20, verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Марка и модель',
                'verbose_name_plural': 'Марки и модели',
                'ordering': ['mark'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='Типы')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Wheels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(db_index=True, max_length=20, verbose_name='Марка')),
                ('model', models.CharField(db_index=True, max_length=20, verbose_name='Модель')),
                ('diameter', models.FloatField(blank=True, null=True, verbose_name='Диаметр')),
            ],
            options={
                'verbose_name': 'Колёса',
                'verbose_name_plural': 'Колёса',
                'ordering': ['mark'],
            },
        ),
        migrations.RemoveField(
            model_name='bsles',
            name='release',
        ),
        migrations.AddField(
            model_name='bsles',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Вес'),
        ),
        migrations.AddField(
            model_name='bsles',
            name='frame',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Bicycles.frame', verbose_name='Рама'),
        ),
        migrations.AddField(
            model_name='bsles',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Bicycles.type', verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='bsles',
            name='wheels',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Bicycles.wheels', verbose_name='Рама'),
        ),
        migrations.AlterField(
            model_name='bsles',
            name='stamp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Bicycles.marks', verbose_name='Марка - Модель'),
        ),
    ]
